DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sex TEXT NOT NULL,
  age TEXT NOT NULL,
  country TEXT NOT NULL
);

CREATE TABLE ans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  category TEXT NOT NULL,
  id_image_1 TEXT NOT NULL,
  id_image_2 TEXT NOT NULL,
  choice TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);